Equality
```{r}
"Rchitect" != "rchitect"
TRUE == FALSE
-6*14 != 17-101
TRUE == 1

-6 * 5 + 2 >= -10+1
```
Compare vectors

```{r}
linkedin <- c(16,9,13,5,2,17,14)
facebook <- c(17,9,16,5,2,13,14)

linkedin>15

facebook <= 5

linkedin> facebook

```

compare matrices

```{r}
views <- matrix(c(linkedin, facebook), nrow=2, byrow = TRUE)
views
views ==13
views <= 14
```

& and |

```{r}
linkedin
last<- tail (linkedin, 3)
last > 5 | last < 10
last>15 & last <= 20

linkedin>10 & facebook <10

```

The if statement

```{r}
medium <- "Linkedin"
num_views <- 14

if(medium == "Linkedin"){
  print("Showing Linkedin information")
}

 
```

```{r}
result <- ""
number <- 6

if(number < 10){
  if(number < 5){
    result <- "extra small"
  }
  else {
    result <- "small"
  }
}else if(number<100){
  result <- "medium"
}else{
  result <- "large"
}

print(result)
```

Write a while lopp

```{r}
speed <- 64

while(speed > 30){
  print("slow down! ")
  print(speed)
  speed <- speed -7
}

```
```{r}
 
```

Loop over a vector
```{r}
linkedin <- c(16,9,13,5,2,17,14)
for(l in linkedin){
  print(l)
}

for(i in 1:length((linkedin))){
  print(linkedin[i])
}
```

Loop over a list

```{r}
nyc <- list(pop = 840537, boroughs=c("Manhathan", "Bronx", "Brooklyn", "Queens", "Staten Island"), capital = FALSE)

for(n in nyc){
  print(n)
}


for(i in 1:length(nyc)){
print(nyc[[i]])
}

```

for in matrix
```{r}
new_hope 
return_jedi <- c(309.306,165.38)

box_office <- c(new_hope, empire_strikes, return_jedi)

for(i in 1:nrow(stars_wars_matrix)){
  for(j in 1:ncol(stars_wars_matrix)){
    print(paste("on row", i , " and column ", j, "te board contains", stars_wars_matrix[i, j]))
    
  }
}

```


```{r}
linkedin <- c(16,9,13,5,2,17,14)
for(li in linkedin){
  if(li>10){
    print("Yo're popular!")
  }else{
    print("Be more visible!")
  }
  if(li>16){
    print("This is ridiculous, I'm outta here!")
    break
  }
  if(li>5){
    "This is so emarrasing!"
  }
  print(li)
}
```

