Funcionts

```{r}
length(linkedin)
head(linkedin,2)
tail(linkedin, 2)

help("length")
?length

list()

```

Use a function
```{r}
avg_li <- mean(linkedin)
avg_li
sum(linkedin)
abs(linkedin)
```

Write your own function
```{r}
pow_two <- function(arg){
  arg **2
}
pow_two(2)

sum_abs <- function(arg1, arg2){
  abs(arg1)+ abs(arg2)
}

sum_abs(-2,3)

hello <- function(){
  print("Hi there")
  return(TRUE)
}

hello()

interpret <-function(num_views){
  if(num_views>15){
    print("You're pupular!")
    return(num_views)
  }else{
    print("Try to be more visible!")
  }
}

 library(ggplot2)

mtcars
qplot(mtcars$wt, mtcars$hp)

```



The apply family
lappy
```{r}

pionners <- c("GAUSS:1777", "BAYES:1702", "PASCAL:1623", "PEARSON:1857")
split_math <- strsplit(pionners, split = ":")
split_math

split_low <- lapply(split_math, tolower)
split_low

select_first <- function(x){
  x[1]
}

names<- lapply(split_low, select_first)

 
```


lapply and anonymous functions
```{r}
split_low
names <- lapply(split_low, function(x){x[1]})
years <- lapply(split_low, function(x){x[2]})
```

Use lapply with additional arguments
```{r}

select_el <- function(x, index){
  x[index]
}

select_el(split_low, 1)

names <- lapply(split_low, select_el, 1)
years <- lapply(split_low, select_el, 2)
names
 
```

sapply
```{r}

names <- sapply(split_low, select_el, 1)

extreme_avg <- function(x){
  (min(x)+max(x))/2
}

vect1 <- c(3,8,7,6)
vect2 <- c(8,8,7,2)
vect3 <- c(10,1,11,6)

temp <- list(vect1, vect2, vect3)

sapply(temp, extreme_avg)
lapply(temp, extreme_avg)

```

vapply
```{r}

basics <- function(x){
  c(min = min(x), mean = mean(x), max= max(x))
}
 

```


Mathematical utilites
```{r}

errors <= )  
```

